### ISSUE TITLE
a component should have component meta data

### ISSUE THREAD

**Issue by trombik** [UncleRus/esp-idf-lib#260]
**Device type**:

- [x] ESP32
- [x] ESP8226

**Framework version**:

does not really matter.

**Describe the bug**:

Each component should have meta data. the meta data can be used for automation, and,  possibly, other things.

an example meta data file for `ads111x` (`components/ads111x/.eil.yml`) looks like this:

```yaml
---
components:
  - name: foo
    group: ADC/DAC
    licenses:
      - name: ISC
    targets:
      - name: esp32
    description: foo driver
  - name: ads111x
    description: |
      Driver for ADS1113/ADS1114/ADS1115 and ADS1013/ADS1014/ADS1015 I2C ADC
    group: ADC/DAC
    groups: []
    code_owners:
      - name: UncleRus
    depneds:
      - name: i2cdev
      - name: log
      - name: esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
    licenses:
      - name: BSD-3-Clause
    copyrights:
      - name: UncleRus
        full_name: Ruslan V. Uss
        email: unclerus@gmail.com
        year: 2016
      - name: dianlight
        full_name: Lucio Tarantino
        year: 2020
```
for starter, it helps to generate `README.md`. `Components` section would look like this:

```erb
## Components
<%
    groups = []
    @components.each do |c| 
      c["components"].each do |sub_c|
        groups << sub_c["group"]
      end 
    end 
    groups = groups.uniq.sort
-%>
<% groups.each do |g| %>
### <%= g %> libraries

| Component      | Description                                                             | License | ESP8266 | Thread safety
|----------------|-------------------------------------------------------------------------|---------|---------|---------------
<%
  group_components = []
  @components.each do |component|
    group_components += component["components"].select { |sub_component| sub_component["group"] == g } 
  end 
  group_components.each do |c| 
    name = c["name"]
    license = c["licenses"].map { |l| l["name"] }.join(", ")
    targets = c["targets"].map { |t| t["name"] }
    esp8266_support = targets.include?("esp8266") ? "Yes" : "No"
    thread_safe = c["thread_safe"] == "yes" ? "Yes" : "No"
    description = c["description"].chomp -%> 
| **<%= name %>** | <%= description %> | <%= license %> | <%= esp8266_support %> | <%= thread_safe %>
<% end -%> 
<% end -%> 
```

the meta data file format is not yet fixed.

other possibilities include:

* skip compilation of some components if they are not needed
* ensure the license is valid
* ensure the copyright holders are properly attributed
* clarify code owner
* generate other meta data
